name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            platform: darwin
            arch: universal
          - os: ubuntu-latest
            platform: linux
            arch: x64
          - os: windows-latest
            platform: win32
            arch: x64

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            rpm \
            libarchive-tools \
            imagemagick \
            fpm \
            build-essential \
            libnss3-dev \
            libatk-bridge2.0-dev \
            libdrm2 \
            libxss1 \
            libgconf-2-4 \
            libxrandr2 \
            libasound2-dev \
            libpangocairo-1.0-0 \
            libatk1.0-dev \
            libcairo-gobject2 \
            libgtk-3-dev \
            libgdk-pixbuf2.0-dev \
            libvips-dev \
            python3-dev

      - name: Setup virtual display (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          sleep 2
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Install macOS icon tools
        if: matrix.os == 'macos-latest'
        run: |
          # macOS should have sips and iconutil built-in
          echo "macOS icon tools are built-in"

      - name: Install Windows icon tools (skip)
        if: matrix.os == 'windows-latest'
        run: |
          echo "Skipping icon generation on Windows - using pre-built icons"

      - name: Generate icons (Unix)
        if: matrix.os != 'windows-latest'
        run: npm run generate-icons || echo "Icon generation failed, continuing with existing icons"
        
      - name: Generate icons (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          echo "Attempting icon generation on Windows..."
          npm run generate-icons
        continue-on-error: true

      # macOS Code Signing
      - name: Import macOS certificates
        if: matrix.os == 'macos-latest' && env.APPLE_CERT_BASE64
        env:
          APPLE_CERT_BASE64: ${{ secrets.APPLE_CERT_BASE64 }}
          APPLE_CERT_PASSWORD: ${{ secrets.APPLE_CERT_PASSWORD }}
        run: |
          CERTIFICATE_PATH=$RUNNER_TEMP/certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          
          echo $APPLE_CERT_BASE64 | base64 --decode > $CERTIFICATE_PATH
          
          security create-keychain -p "$APPLE_CERT_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$APPLE_CERT_PASSWORD" $KEYCHAIN_PATH
          
          security import $CERTIFICATE_PATH -P "$APPLE_CERT_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

      # Windows Code Signing
      - name: Import Windows certificate
        if: matrix.os == 'windows-latest' && env.WINDOWS_CERT_BASE64
        env:
          WINDOWS_CERT_BASE64: ${{ secrets.WINDOWS_CERT_BASE64 }}
        run: |
          $cert = [System.Convert]::FromBase64String($env:WINDOWS_CERT_BASE64)
          $certPath = "$env:RUNNER_TEMP\certificate.pfx"
          [System.IO.File]::WriteAllBytes($certPath, $cert)
          echo "WINDOWS_CERT_FILE=$certPath" >> $env:GITHUB_ENV

      - name: Debug environment (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "DISPLAY=$DISPLAY"
          ps aux | grep Xvfb || echo "No Xvfb process found"
          ls -la src/assets/
          echo "Checking required icon files..."
          test -f src/assets/icon.png && echo "✓ icon.png exists" || echo "✗ icon.png missing"
          test -f src/assets/icon.icns && echo "✓ icon.icns exists" || echo "✗ icon.icns missing"
          test -f src/assets/icon.ico && echo "✓ icon.ico exists" || echo "✗ icon.ico missing"
          
      - name: Build with Electron Forge
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_IDENTITY: ${{ secrets.APPLE_IDENTITY }}
          WINDOWS_CERT_PASSWORD: ${{ secrets.WINDOWS_CERT_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: electron-forge:*
          npm_config_cache: ${{ github.workspace }}/.npm
        run: |
          echo "Building for platform: ${{ matrix.platform }}"
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          npm run make

      - name: List build artifacts
        run: |
          echo "Contents of out/make:"
          ls -la out/make/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-${{ matrix.arch }}-distributables
          path: |
            out/make/**/*.deb
            out/make/**/*.rpm
            out/make/**/*.zip
            out/make/**/*.dmg
            out/make/**/*.exe
            out/make/**/*.AppImage
          retention-days: 7

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name || format('v{0}', github.event.inputs.version) }}
          name: ParaFile Desktop ${{ github.ref_name || format('v{0}', github.event.inputs.version) }}
          body: |
            ## ParaFile Desktop Release
            
            AI-powered document organization and renaming application.
            
            ### Download Instructions
            
            #### macOS
            - Download the `.dmg` file
            - Open the DMG and drag ParaFile Desktop to Applications
            - On first launch, right-click and select "Open" to bypass Gatekeeper
            
            #### Windows
            - Download the `.exe` installer
            - Run the installer and follow the prompts
            - The app will be available in your Start Menu
            
            #### Linux
            - **Debian/Ubuntu**: Download and install the `.deb` file
            - **Fedora/RHEL**: Download and install the `.rpm` file
            - **Other**: Download the `.zip` file and extract
            
            ### What's New
            - See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/docs/CHANGELOG.md) for details
          draft: true
          prerelease: false
          files: |
            artifacts/**/*.deb
            artifacts/**/*.rpm
            artifacts/**/*.zip
            artifacts/**/*.dmg
            artifacts/**/*.exe
            artifacts/**/*.AppImage


  update-latest-json:
    needs: release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create latest.json for auto-updater
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          cat > latest.json << EOF
          {
            "version": "$VERSION",
            "releaseDate": "$(date -u +%Y-%m-%dT%H:%M:%S.000Z)",
            "path": "https://github.com/${{ github.repository }}/releases/download/v$VERSION/",
            "files": {
              "mac": {
                "url": "ParaFile-Desktop-$VERSION.dmg",
                "sha512": ""
              },
              "windows": {
                "url": "ParaFile-Desktop-Setup-$VERSION.exe",
                "sha512": ""
              },
              "linux": {
                "url": "parafile-desktop_$VERSION_amd64.deb",
                "sha512": ""
              }
            }
          }
          EOF

      - name: Upload latest.json to release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          files: latest.json